// AUTOGENERATED: DO NOT MANUALLY EDIT THIS FILE
export const ICLSynchronicityPriceAdapter_ABI = [
  {
    "type": "function",
    "name": "decimals",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "description",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "latestAnswer",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "int256",
        "internalType": "int256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "error",
    "name": "DecimalsAboveLimit",
    "inputs": []
  },
  {
    "type": "error",
    "name": "DecimalsNotEqual",
    "inputs": []
  },
  {
    "type": "error",
    "name": "RatioOutOfBounds",
    "inputs": []
  }
] as const;