// AUTOGENERATED: DO NOT MANUALLY EDIT THIS FILE
export const IEmissionManager_ABI = [
  {
    "type": "function",
    "name": "configureAssets",
    "inputs": [
      {
        "name": "config",
        "type": "tuple[]",
        "internalType": "struct RewardsDataTypes.RewardsConfigInput[]",
        "components": [
          {
            "name": "emissionPerSecond",
            "type": "uint88",
            "internalType": "uint88"
          },
          {
            "name": "totalSupply",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "distributionEnd",
            "type": "uint32",
            "internalType": "uint32"
          },
          {
            "name": "asset",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "reward",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "transferStrategy",
            "type": "address",
            "internalType": "contract ITransferStrategyBase"
          },
          {
            "name": "rewardOracle",
            "type": "address",
            "internalType": "contract AggregatorInterface"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "getEmissionAdmin",
    "inputs": [
      {
        "name": "reward",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getRewardsController",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IRewardsController"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setClaimer",
    "inputs": [
      {
        "name": "user",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "claimer",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setDistributionEnd",
    "inputs": [
      {
        "name": "asset",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "reward",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "newDistributionEnd",
        "type": "uint32",
        "internalType": "uint32"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setEmissionAdmin",
    "inputs": [
      {
        "name": "reward",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "admin",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setEmissionPerSecond",
    "inputs": [
      {
        "name": "asset",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "rewards",
        "type": "address[]",
        "internalType": "address[]"
      },
      {
        "name": "newEmissionsPerSecond",
        "type": "uint88[]",
        "internalType": "uint88[]"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setRewardOracle",
    "inputs": [
      {
        "name": "reward",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "rewardOracle",
        "type": "address",
        "internalType": "contract AggregatorInterface"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setRewardsController",
    "inputs": [
      {
        "name": "controller",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setTransferStrategy",
    "inputs": [
      {
        "name": "reward",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "transferStrategy",
        "type": "address",
        "internalType": "contract ITransferStrategyBase"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "EmissionAdminUpdated",
    "inputs": [
      {
        "name": "reward",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "oldAdmin",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newAdmin",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  }
] as const;