// AUTOGENERATED: DO NOT MANUALLY EDIT THIS FILE
export const IPayloadsController_ABI = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "crossChainController",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "messageOriginator",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "originChainId",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "receive",
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "CROSS_CHAIN_CONTROLLER",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "EXPIRATION_DELAY",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint40",
        "internalType": "uint40"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "GRACE_PERIOD",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint40",
        "internalType": "uint40"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "MAX_EXECUTION_DELAY",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint40",
        "internalType": "uint40"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MESSAGE_ORIGINATOR",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MIN_EXECUTION_DELAY",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint40",
        "internalType": "uint40"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "ORIGIN_CHAIN_ID",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "cancelPayload",
    "inputs": [
      {
        "name": "payloadId",
        "type": "uint40",
        "internalType": "uint40"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "createPayload",
    "inputs": [
      {
        "name": "actions",
        "type": "tuple[]",
        "internalType": "struct IPayloadsControllerCore.ExecutionAction[]",
        "components": [
          {
            "name": "target",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "withDelegateCall",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "accessLevel",
            "type": "uint8",
            "internalType": "enum PayloadsControllerUtils.AccessControl"
          },
          {
            "name": "value",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "signature",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "callData",
            "type": "bytes",
            "internalType": "bytes"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint40",
        "internalType": "uint40"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "decodeMessage",
    "inputs": [
      {
        "name": "message",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint40",
        "internalType": "uint40"
      },
      {
        "name": "",
        "type": "uint8",
        "internalType": "enum PayloadsControllerUtils.AccessControl"
      },
      {
        "name": "",
        "type": "uint40",
        "internalType": "uint40"
      }
    ],
    "stateMutability": "pure"
  },
  {
    "type": "function",
    "name": "emergencyEtherTransfer",
    "inputs": [
      {
        "name": "to",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "emergencyTokenTransfer",
    "inputs": [
      {
        "name": "erc20Token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "to",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "executePayload",
    "inputs": [
      {
        "name": "payloadId",
        "type": "uint40",
        "internalType": "uint40"
      }
    ],
    "outputs": [],
    "stateMutability": "payable"
  },
  {
    "type": "function",
    "name": "getExecutorSettingsByAccessControl",
    "inputs": [
      {
        "name": "accessControl",
        "type": "uint8",
        "internalType": "enum PayloadsControllerUtils.AccessControl"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct IPayloadsControllerCore.ExecutorConfig",
        "components": [
          {
            "name": "executor",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "delay",
            "type": "uint40",
            "internalType": "uint40"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getPayloadById",
    "inputs": [
      {
        "name": "payloadId",
        "type": "uint40",
        "internalType": "uint40"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct IPayloadsControllerCore.Payload",
        "components": [
          {
            "name": "creator",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "maximumAccessLevelRequired",
            "type": "uint8",
            "internalType": "enum PayloadsControllerUtils.AccessControl"
          },
          {
            "name": "state",
            "type": "uint8",
            "internalType": "enum IPayloadsControllerCore.PayloadState"
          },
          {
            "name": "createdAt",
            "type": "uint40",
            "internalType": "uint40"
          },
          {
            "name": "queuedAt",
            "type": "uint40",
            "internalType": "uint40"
          },
          {
            "name": "executedAt",
            "type": "uint40",
            "internalType": "uint40"
          },
          {
            "name": "cancelledAt",
            "type": "uint40",
            "internalType": "uint40"
          },
          {
            "name": "expirationTime",
            "type": "uint40",
            "internalType": "uint40"
          },
          {
            "name": "delay",
            "type": "uint40",
            "internalType": "uint40"
          },
          {
            "name": "gracePeriod",
            "type": "uint40",
            "internalType": "uint40"
          },
          {
            "name": "actions",
            "type": "tuple[]",
            "internalType": "struct IPayloadsControllerCore.ExecutionAction[]",
            "components": [
              {
                "name": "target",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "withDelegateCall",
                "type": "bool",
                "internalType": "bool"
              },
              {
                "name": "accessLevel",
                "type": "uint8",
                "internalType": "enum PayloadsControllerUtils.AccessControl"
              },
              {
                "name": "value",
                "type": "uint256",
                "internalType": "uint256"
              },
              {
                "name": "signature",
                "type": "string",
                "internalType": "string"
              },
              {
                "name": "callData",
                "type": "bytes",
                "internalType": "bytes"
              }
            ]
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getPayloadState",
    "inputs": [
      {
        "name": "payloadId",
        "type": "uint40",
        "internalType": "uint40"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "enum IPayloadsControllerCore.PayloadState"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getPayloadsCount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint40",
        "internalType": "uint40"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "guardian",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "initialize",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "guardian",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "executors",
        "type": "tuple[]",
        "internalType": "struct IPayloadsControllerCore.UpdateExecutorInput[]",
        "components": [
          {
            "name": "accessLevel",
            "type": "uint8",
            "internalType": "enum PayloadsControllerUtils.AccessControl"
          },
          {
            "name": "executorConfig",
            "type": "tuple",
            "internalType": "struct IPayloadsControllerCore.ExecutorConfig",
            "components": [
              {
                "name": "executor",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "delay",
                "type": "uint40",
                "internalType": "uint40"
              }
            ]
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "maxRescue",
    "inputs": [
      {
        "name": "erc20Token",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "owner",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "receiveCrossChainMessage",
    "inputs": [
      {
        "name": "originSender",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "originChainId",
        "type": "uint256",
        "internalType": "uint256"
      },
      {
        "name": "message",
        "type": "bytes",
        "internalType": "bytes"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "renounceOwnership",
    "inputs": [],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "transferOwnership",
    "inputs": [
      {
        "name": "newOwner",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "updateExecutors",
    "inputs": [
      {
        "name": "executors",
        "type": "tuple[]",
        "internalType": "struct IPayloadsControllerCore.UpdateExecutorInput[]",
        "components": [
          {
            "name": "accessLevel",
            "type": "uint8",
            "internalType": "enum PayloadsControllerUtils.AccessControl"
          },
          {
            "name": "executorConfig",
            "type": "tuple",
            "internalType": "struct IPayloadsControllerCore.ExecutorConfig",
            "components": [
              {
                "name": "executor",
                "type": "address",
                "internalType": "address"
              },
              {
                "name": "delay",
                "type": "uint40",
                "internalType": "uint40"
              }
            ]
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "updateGuardian",
    "inputs": [
      {
        "name": "newGuardian",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "whoCanRescue",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "event",
    "name": "ERC20Rescued",
    "inputs": [
      {
        "name": "caller",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "token",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "to",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ExecutorSet",
    "inputs": [
      {
        "name": "accessLevel",
        "type": "uint8",
        "indexed": true,
        "internalType": "enum PayloadsControllerUtils.AccessControl"
      },
      {
        "name": "executor",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "delay",
        "type": "uint40",
        "indexed": false,
        "internalType": "uint40"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "GuardianUpdated",
    "inputs": [
      {
        "name": "oldGuardian",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      },
      {
        "name": "newGuardian",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "Initialized",
    "inputs": [
      {
        "name": "version",
        "type": "uint8",
        "indexed": false,
        "internalType": "uint8"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "NativeTokensRescued",
    "inputs": [
      {
        "name": "caller",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "to",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "OwnershipTransferred",
    "inputs": [
      {
        "name": "previousOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newOwner",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PayloadCancelled",
    "inputs": [
      {
        "name": "payloadId",
        "type": "uint40",
        "indexed": false,
        "internalType": "uint40"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PayloadCreated",
    "inputs": [
      {
        "name": "payloadId",
        "type": "uint40",
        "indexed": true,
        "internalType": "uint40"
      },
      {
        "name": "creator",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "actions",
        "type": "tuple[]",
        "indexed": false,
        "internalType": "struct IPayloadsControllerCore.ExecutionAction[]",
        "components": [
          {
            "name": "target",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "withDelegateCall",
            "type": "bool",
            "internalType": "bool"
          },
          {
            "name": "accessLevel",
            "type": "uint8",
            "internalType": "enum PayloadsControllerUtils.AccessControl"
          },
          {
            "name": "value",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "signature",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "callData",
            "type": "bytes",
            "internalType": "bytes"
          }
        ]
      },
      {
        "name": "maximumAccessLevelRequired",
        "type": "uint8",
        "indexed": true,
        "internalType": "enum PayloadsControllerUtils.AccessControl"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PayloadExecuted",
    "inputs": [
      {
        "name": "payloadId",
        "type": "uint40",
        "indexed": false,
        "internalType": "uint40"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PayloadExecutionMessageReceived",
    "inputs": [
      {
        "name": "originSender",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "originChainId",
        "type": "uint256",
        "indexed": true,
        "internalType": "uint256"
      },
      {
        "name": "delivered",
        "type": "bool",
        "indexed": true,
        "internalType": "bool"
      },
      {
        "name": "message",
        "type": "bytes",
        "indexed": false,
        "internalType": "bytes"
      },
      {
        "name": "reason",
        "type": "bytes",
        "indexed": false,
        "internalType": "bytes"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PayloadQueued",
    "inputs": [
      {
        "name": "payloadId",
        "type": "uint40",
        "indexed": false,
        "internalType": "uint40"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "EthTransferFailed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OnlyGuardianInvalidCaller",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "OnlyGuardianOrOwnerInvalidCaller",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "OnlyRescueGuardian",
    "inputs": []
  },
  {
    "type": "error",
    "name": "OwnableInvalidOwner",
    "inputs": [
      {
        "name": "owner",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "OwnableUnauthorizedAccount",
    "inputs": [
      {
        "name": "account",
        "type": "address",
        "internalType": "address"
      }
    ]
  },
  {
    "type": "error",
    "name": "SafeERC20FailedOperation",
    "inputs": [
      {
        "name": "token",
        "type": "address",
        "internalType": "address"
      }
    ]
  }
] as const;