// AUTOGENERATED: DO NOT MANUALLY EDIT THIS FILE
export const IPendlePriceCapAdapter_ABI = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "params",
        "type": "tuple",
        "internalType": "struct IPendlePriceCapAdapter.PendlePriceCapAdapterParams",
        "components": [
          {
            "name": "assetToUsdAggregator",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "pendlePrincipalToken",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "maxDiscountRatePerYear",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "discountRatePerYear",
            "type": "uint64",
            "internalType": "uint64"
          },
          {
            "name": "aclManager",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "description",
            "type": "string",
            "internalType": "string"
          }
        ]
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "ACL_MANAGER",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IACLManager"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "ASSET_TO_USD_AGGREGATOR",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IChainlinkAggregator"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "DECIMALS",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MATURITY",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_DISCOUNT_RATE_PER_YEAR",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "PENDLE_PRINCIPAL_TOKEN",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IPendlePrincipalToken"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "PERCENTAGE_FACTOR",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "SECONDS_PER_YEAR",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "decimals",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "description",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "discountRatePerYear",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getCurrentDiscount",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "latestAnswer",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "int256",
        "internalType": "int256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setDiscountRatePerYear",
    "inputs": [
      {
        "name": "discountRatePerYear_",
        "type": "uint64",
        "internalType": "uint64"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "DiscountRatePerYearUpdated",
    "inputs": [
      {
        "name": "oldDiscountRatePerYear",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      },
      {
        "name": "newDiscountRatePerYear",
        "type": "uint64",
        "indexed": false,
        "internalType": "uint64"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "CallerIsNotRiskOrPoolAdmin",
    "inputs": []
  },
  {
    "type": "error",
    "name": "DecimalsAboveLimit",
    "inputs": []
  },
  {
    "type": "error",
    "name": "DecimalsNotEqual",
    "inputs": []
  },
  {
    "type": "error",
    "name": "DiscountExceeds100Percent",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidNewDiscountRatePerYear",
    "inputs": []
  },
  {
    "type": "error",
    "name": "MaturityHasAlreadyPassed",
    "inputs": []
  },
  {
    "type": "error",
    "name": "RatioOutOfBounds",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroMaxDiscount",
    "inputs": []
  }
] as const;