// AUTOGENERATED: DO NOT MANUALLY EDIT THIS FILE
export const IPriceCapAdapterStable_ABI = [
  {
    "type": "constructor",
    "inputs": [
      {
        "name": "capAdapterStableParams",
        "type": "tuple",
        "internalType": "struct IPriceCapAdapterStable.CapAdapterStableParams",
        "components": [
          {
            "name": "aclManager",
            "type": "address",
            "internalType": "contract IACLManager"
          },
          {
            "name": "assetToUsdAggregator",
            "type": "address",
            "internalType": "contract IChainlinkAggregator"
          },
          {
            "name": "adapterDescription",
            "type": "string",
            "internalType": "string"
          },
          {
            "name": "priceCap",
            "type": "int256",
            "internalType": "int256"
          }
        ]
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "ACL_MANAGER",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IACLManager"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "ASSET_TO_USD_AGGREGATOR",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IChainlinkAggregator"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "MAX_STABLE_CAP_VALUE",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "int256",
        "internalType": "int256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "decimals",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "uint8",
        "internalType": "uint8"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "description",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "string",
        "internalType": "string"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getPriceCap",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "int256",
        "internalType": "int256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isCapped",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "latestAnswer",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "int256",
        "internalType": "int256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "setPriceCap",
    "inputs": [
      {
        "name": "priceCap",
        "type": "int256",
        "internalType": "int256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "PriceCapUpdated",
    "inputs": [
      {
        "name": "priceCap",
        "type": "int256",
        "indexed": false,
        "internalType": "int256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "ACLManagerIsZeroAddress",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CallerIsNotRiskOrPoolAdmin",
    "inputs": []
  },
  {
    "type": "error",
    "name": "CapLowerThanActualPrice",
    "inputs": []
  },
  {
    "type": "error",
    "name": "DecimalsAboveLimit",
    "inputs": []
  },
  {
    "type": "error",
    "name": "DecimalsNotEqual",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidNewPriceCap",
    "inputs": []
  },
  {
    "type": "error",
    "name": "RatioOutOfBounds",
    "inputs": []
  }
] as const;