// AUTOGENERATED: DO NOT MANUALLY EDIT THIS FILE
export const IUmbrella_ABI = [
  {
    "type": "function",
    "name": "POOL",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IPool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "POOL_ADDRESSES_PROVIDER",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract IPoolAddressesProvider"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "SLASHED_FUNDS_RECIPIENT",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "SUPER_ADMIN",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "TRANSPARENT_PROXY_FACTORY",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "contract ITransparentProxyFactory"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "UMBRELLA_STAKE_TOKEN_IMPL",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "coverDeficitOffset",
    "inputs": [
      {
        "name": "reserve",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "coverPendingDeficit",
    "inputs": [
      {
        "name": "reserve",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "coverReserveDeficit",
    "inputs": [
      {
        "name": "reserve",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "createStakeTokens",
    "inputs": [
      {
        "name": "stakeTokenSetups",
        "type": "tuple[]",
        "internalType": "struct IUmbrellaStkManager.StakeTokenSetup[]",
        "components": [
          {
            "name": "underlying",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "cooldown",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "unstakeWindow",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "suffix",
            "type": "string",
            "internalType": "string"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "stakeTokens",
        "type": "address[]",
        "internalType": "address[]"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "emergencyEtherTransferStk",
    "inputs": [
      {
        "name": "stk",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "to",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "emergencyTokenTransferStk",
    "inputs": [
      {
        "name": "stk",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "erc20Token",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "to",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "getDeficitOffset",
    "inputs": [
      {
        "name": "reserve",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getPendingDeficit",
    "inputs": [
      {
        "name": "reserve",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getReserveSlashingConfig",
    "inputs": [
      {
        "name": "reserve",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "umbrellaStake",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple",
        "internalType": "struct IUmbrellaConfiguration.SlashingConfig",
        "components": [
          {
            "name": "umbrellaStake",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "umbrellaStakeUnderlyingOracle",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "liquidationFee",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getReserveSlashingConfigs",
    "inputs": [
      {
        "name": "reserve",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "tuple[]",
        "internalType": "struct IUmbrellaConfiguration.SlashingConfig[]",
        "components": [
          {
            "name": "umbrellaStake",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "umbrellaStakeUnderlyingOracle",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "liquidationFee",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getStakeTokenData",
    "inputs": [
      {
        "name": "umbrellaStake",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "stakeTokenData",
        "type": "tuple",
        "internalType": "struct IUmbrellaConfiguration.StakeTokenData",
        "components": [
          {
            "name": "underlyingOracle",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "reserve",
            "type": "address",
            "internalType": "address"
          }
        ]
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "getStkTokens",
    "inputs": [],
    "outputs": [
      {
        "name": "",
        "type": "address[]",
        "internalType": "address[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isReserveSlashable",
    "inputs": [
      {
        "name": "reserve",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "flag",
        "type": "bool",
        "internalType": "bool"
      },
      {
        "name": "amount",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "isUmbrellaStkToken",
    "inputs": [
      {
        "name": "stakeToken",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "bool",
        "internalType": "bool"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "latestUnderlyingAnswer",
    "inputs": [
      {
        "name": "umbrellaStake",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "latestAnswer",
        "type": "int256",
        "internalType": "int256"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "pauseStk",
    "inputs": [
      {
        "name": "stk",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "predictStakeTokensAddresses",
    "inputs": [
      {
        "name": "stakeSetups",
        "type": "tuple[]",
        "internalType": "struct IUmbrellaStkManager.StakeTokenSetup[]",
        "components": [
          {
            "name": "underlying",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "cooldown",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "unstakeWindow",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "suffix",
            "type": "string",
            "internalType": "string"
          }
        ]
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address[]",
        "internalType": "address[]"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "removeSlashingConfigs",
    "inputs": [
      {
        "name": "removalPairs",
        "type": "tuple[]",
        "internalType": "struct IUmbrellaConfiguration.SlashingConfigRemoval[]",
        "components": [
          {
            "name": "reserve",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "umbrellaStake",
            "type": "address",
            "internalType": "address"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setCooldownStk",
    "inputs": [
      {
        "name": "cooldownConfigs",
        "type": "tuple[]",
        "internalType": "struct IUmbrellaStkManager.CooldownConfig[]",
        "components": [
          {
            "name": "umbrellaStake",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "newCooldown",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setDeficitOffset",
    "inputs": [
      {
        "name": "reserve",
        "type": "address",
        "internalType": "address"
      },
      {
        "name": "newDeficitOffset",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "setUnstakeWindowStk",
    "inputs": [
      {
        "name": "unstakeWindowConfigs",
        "type": "tuple[]",
        "internalType": "struct IUmbrellaStkManager.UnstakeWindowConfig[]",
        "components": [
          {
            "name": "umbrellaStake",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "newUnstakeWindow",
            "type": "uint256",
            "internalType": "uint256"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "slash",
    "inputs": [
      {
        "name": "reserve",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "uint256",
        "internalType": "uint256"
      }
    ],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "tokenForDeficitCoverage",
    "inputs": [
      {
        "name": "reserve",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [
      {
        "name": "",
        "type": "address",
        "internalType": "address"
      }
    ],
    "stateMutability": "view"
  },
  {
    "type": "function",
    "name": "unpauseStk",
    "inputs": [
      {
        "name": "stk",
        "type": "address",
        "internalType": "address"
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "function",
    "name": "updateSlashingConfigs",
    "inputs": [
      {
        "name": "slashingConfigs",
        "type": "tuple[]",
        "internalType": "struct IUmbrellaConfiguration.SlashingConfigUpdate[]",
        "components": [
          {
            "name": "reserve",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "umbrellaStake",
            "type": "address",
            "internalType": "address"
          },
          {
            "name": "liquidationFee",
            "type": "uint256",
            "internalType": "uint256"
          },
          {
            "name": "umbrellaStakeUnderlyingOracle",
            "type": "address",
            "internalType": "address"
          }
        ]
      }
    ],
    "outputs": [],
    "stateMutability": "nonpayable"
  },
  {
    "type": "event",
    "name": "DeficitOffsetChanged",
    "inputs": [
      {
        "name": "reserve",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newDeficitOffset",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "DeficitOffsetCovered",
    "inputs": [
      {
        "name": "reserve",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PendingDeficitChanged",
    "inputs": [
      {
        "name": "reserve",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "newPendingDeficit",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "PendingDeficitCovered",
    "inputs": [
      {
        "name": "reserve",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "ReserveDeficitCovered",
    "inputs": [
      {
        "name": "reserve",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SlashingConfigurationChanged",
    "inputs": [
      {
        "name": "reserve",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "umbrellaStake",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "liquidationFee",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "umbrellaStakeUnderlyingOracle",
        "type": "address",
        "indexed": false,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "SlashingConfigurationRemoved",
    "inputs": [
      {
        "name": "reserve",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "umbrellaStake",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "StakeTokenSlashed",
    "inputs": [
      {
        "name": "reserve",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "umbrellaStake",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "amount",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      },
      {
        "name": "fee",
        "type": "uint256",
        "indexed": false,
        "internalType": "uint256"
      }
    ],
    "anonymous": false
  },
  {
    "type": "event",
    "name": "UmbrellaStakeTokenCreated",
    "inputs": [
      {
        "name": "umbrellaStake",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "underlying",
        "type": "address",
        "indexed": true,
        "internalType": "address"
      },
      {
        "name": "name",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      },
      {
        "name": "symbol",
        "type": "string",
        "indexed": false,
        "internalType": "string"
      }
    ],
    "anonymous": false
  },
  {
    "type": "error",
    "name": "CannotSlash",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ConfigurationHasNotBeenSet",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ConfigurationNotExist",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidLiquidationFee",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidNumberOfDecimals",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidOraclePrice",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidReserve",
    "inputs": []
  },
  {
    "type": "error",
    "name": "InvalidStakeToken",
    "inputs": []
  },
  {
    "type": "error",
    "name": "NotImplemented",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReserveCoverageNotSetup",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ReserveIsConfigured",
    "inputs": []
  },
  {
    "type": "error",
    "name": "TooMuchDeficitOffsetReduction",
    "inputs": []
  },
  {
    "type": "error",
    "name": "UmbrellaStakeAlreadySetForAnotherReserve",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroAddress",
    "inputs": []
  },
  {
    "type": "error",
    "name": "ZeroDeficitToCover",
    "inputs": []
  }
] as const;